version: '3'
services:
  app:
    build: .
    container_name: krayin-app
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=krayincrm
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: krayin-db
    ports:
      - "3306:3306" # <--- AquÃ­ se expone MySQL al host
    volumes:
      - krayin_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=krayincrm
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password

volumes:
  krayin_db_data:
